name: authyra_flutter
description: >-
  The Flutter integration for Authyra. Provides secure storage, 
  reactive UI components, and official OAuth/Credentials provider
version: 0.1.0
publish_to: none
homepage: https://meragix.github.io/authyra
repository: https://github.com/meragix/authyra
issue_tracker: https://github.com/meragix/authyra/issues
documentation: https://meragix.github.io/authyra

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  authyra:
    path: ../authyra
  dio: ^5.9.1
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  dart_jsonwebtoken: ^3.3.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - auth
  - session
  - oauth
  - jwt
  - security

# The following section is specific to Flutter packages.
flutter:
